apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: mygolang
  name: mypod
spec:
  containers:
  - image: {{ .Values.image }}
    name: mypod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
